config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_scope :customer do
      post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do
    get '/search' => 'posts#search'
    get "/customers/mypage" => "customers#mypage"
    get "/customers/withdraw" => "customers#withdraw"
    resources :customers, only: [:show, :edit, :update] do
      get :favorites, on: :collection
    end
    get "search_tag"=>"posts#search_tag"
    resources :posts do
      get "/myposts" => "posts#myposts"
      resources :favorites, only: [:create, :destroy]
      resources :comments, only: [:create]
    end
  end
  namespace :admin do
    get 'homes/top'
    resources :customers
    resources :posts
    resources :tags, only: [:destroy]
    resources :favorites
    resources :comments
  end

  root to: 'public/homes#top'
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
    before_action :authenticate_admin!
def top
    @tag_list =Tag.all.order(created_at: :desc)
end



end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/views/admin/homes/top.html.erb
<div class="text-success"></p><%= notice %></div>
    <h1 class="mt-5 mb-5 text-center">タグ一覧</h1>
        <table class="table text-center">
            <tr>
                <th>作成日</th>
                <th>タグ名</th>
                <th></th>
            </tr>
          <% @tag_list.each do |list| %>
            <tr>
                <td><%= list.created_at %></td>
                <td><%= list.name %></td>
                <td><%= link_to "削除",  admin_tag_path(list.id), method: :delete, data: {confirm: "削除しますか？"}, class: "btn btn-danger" %></td>
            </tr>
          <% end %>
        </table>