config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_scope :customer do
      post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do
    get '/search' => 'posts#search'
    get "/customers/mypage" => "customers#mypage"
    get "/customers/withdraw" => "customers#withdraw"
    resources :customers, only: [:show, :edit, :update] do
      get :favorites, on: :collection
    end
    get "search_tag"=>"posts#search_tag"
    resources :posts do
      get "/myposts" => "posts#myposts"
      resources :favorites, only: [:create, :destroy]
      resources :comments, only: [:create]
    end
  end
  namespace :admin do
    get 'homes/top'
    resources :customers
    resources :posts
    resources :tags, only: [:destroy]
    resources :favorites
    resources :comments
  end

  root to: 'public/homes#top'
end

app/models/post.rb
class Post < ApplicationRecord
    has_one_attached :image

    belongs_to :customer
    has_many :favorites, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_many :post_tags, dependent: :destroy
    has_many :tags, through: :post_tags

    validates :title,
        length: { minimum: 1, maximun: 50}, presence: true
    validates :introduction,
        length: { minimum: 1, maximum: 500}, presence: true
    validates :image,
        presence: true

    def favorited?(customer)
       favorites.where(customer_id: customer.id).exists?
    end

    def tags_field
        tags.pluck(:name).join(' ')
    end

    def get_image(width, height)
        unless image.attached?
          file_path = Rails.root.join("app/assets/images/no_image.jpeg")
          image.attach(io: File.open(file_path),filename:"default-image.jpg",content_type: "image/jpg")
        end
        image.variant(resize_to_limit: [width, height]).processed
    end

 def save_tag(sent_tags)
        current_tags = self.tags.pluck(:name) unless self.tags.nil?
        old_tags = current_tags - current_tags
        new_tags = sent_tags - current_tags

    old_tags.each do |old|
        self.tags.delete　Tag.find_by(name: old)
    end

    new_tags.uniq.each do |new|
        new_post_tag = Tag.find_or_create_by(name: new)
        self.tags << new_post_tag
    end
 end

    def self.search(keyword)
        # Postからタイトルまたは説明からあいまい検索
        posts = Post.where(["title LIKE ? OR introduction LIKE ?", "%#{keyword}%", "%#{keyword}%"])

        # Tagからnameをあいまい検索
        tags = Tag.where(["name LIKE ? ", "%#{keyword}%"])

        # 空のidを入れる配列を用意
        post_ids = []

        # post_idsにPostから検索した結果のIDたちを入れる
        post_ids += posts.ids

        # タグのあいまい検索をしたものをループする
        tags.each do |tag|
            # ループしたタグに関連づいている記事をpost_idsに次々と入れる
            post_ids += tag.posts.ids
        end

        # 自分自身(Postモデル)からpost_idsのuniqメソッドで重複を除いたものをすべて取得して返す
        Post.where(id: post_ids.uniq)
    end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
    before_action :authenticate_admin!
def index
    @posts=Post.page(params[:page]).per(8).order(created_at: :desc)
end

def show
    @post = Post.find(params[:id])
    @post_tags = @post.tags
    @comments = @post.comments
end

def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path
end

private

def post_params
    params.require(:post).permit(:title, :introduction, :image)
end

end

app/views/admin/posts/index.html.erb
<h2 class="text-center mt-5">投稿一覧</h2>
    <table class="table text-center ml-5 pl-5">
        <tr>
            <th>ポストID</th>
            <th>投稿者</th>
            <th>タイトル</th>
            <th>内容</th>
            <th></th>
        </tr>
        <% @posts.each do |post| %>
            <tr>
                <td><%= post.id %></td>
                <td><%= image_tag post.customer.get_image(200,200) %><br>
                <%= link_to post.customer.full_name, admin_customer_path(post.customer.id) %></td>
                <td><%= link_to post.title, admin_post_path(post.id) %></td>
                <td><%= post.introduction %></td>
                <td></td>
            </tr>
        <% end %>
      <%= paginate @posts %>
    </table>

app/views/admin/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-6">
      <h2 class="pl-5 ml-5 mt-5"><%= @post.title%></h2>
        <div class="mt-5 mb-5">
          <%= link_to admin_comment_path(@post.customer.id) do %>
            <%= image_tag @post.customer.get_image(500,500)%>
          <% end %>
        </div>
        <h4 class="mt-5 mb-5"><%= @post.introduction %></h4>
          <% @post_tags.each do |tag| %>
            <i class="fas fa-hashtag"></i><%= tag.name %>
          <% end %>
            <div class="d-flex justify-content-between">
              <h5 class="mt-5">投稿者:<%= link_to @post.customer.full_name, admin_customer_path(@post.customer.id) %></h5>
              <div><%= link_to "投稿削除", admin_post_path(@post.id), method: :delete, class: "btn btn-danger d-inline" %></div>
            </div>
    </div>

      <div class="col-lg-6">
        <% @comments.each do |comment| %>
          <div class="box2">
            <div class="d-block mb-5">
              <div class="d-inline">コメント：</div><h4 class="d-inline "><%= comment.comment_content %></h4>
            </div>
            <div class="d-block mb-5">
              投稿者：<%= comment.customer.full_name %>
              <%= link_to "コメント削除", admin_comment_path(comment.id), method: :delete, class: "btn btn-danger float-right " %>
            </div>
          </div>
        <% end %>
      </div>
  </div>
</div>

<style>
    .box2{
        padding: 0.5em 1em;
        margin: 2em 0;
        font-weight: bold;
        color: #6091d3;
        background: #FFF;
        border: solid 3px #6091d3;
        border-radius: 10px;
    }

    .box2 p {
        margin: 0;
        padding: 0;
    }
</style>