config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_scope :customer do
      post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do
    get '/search' => 'posts#search'
    get "/customers/mypage" => "customers#mypage"
    get "/customers/withdraw" => "customers#withdraw"
    resources :customers, only: [:show, :edit, :update] do
      get :favorites, on: :collection
    end
    get "search_tag"=>"posts#search_tag"
    resources :posts do
      get "/myposts" => "posts#myposts"
      resources :favorites, only: [:create, :destroy]
      resources :comments, only: [:create]
    end
  end
  namespace :admin do
    get 'homes/top'
    resources :customers
    resources :posts
    resources :tags, only: [:destroy]
    resources :favorites
    resources :comments
  end

  root to: 'public/homes#top'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FacePallet</title>
      <meta name="viewport" content="width=device-width,initial-scale=1">
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
     <% if customer_signed_in? %>
        <nav class="navbar navbar-expand-lg navbar-dark bg-info">
           <%= link_to "Face Pallet", root_path, class: "navbar-brand" %>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span ><%= image_tag current_customer.get_image(50,50), class: "rounded-circle"  %></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                  <li class="nav-item active">
                    <%= link_to "Your Information",customers_mypage_path, class:"nav-link" %>
                  </li>
                  <li class="nav-item active">
                    <%= link_to "Create Post", new_post_path, class:"nav-link" %>
                  </li>
                  <li class="nav-item active">
                     <%= link_to "Post List", posts_path, class:"nav-link" %>
                  </li>
                  <li class="nav-item active">
                    <%= link_to "Log Out", destroy_customer_session_path, method: :delete, class: "nav-link text-white" %>
                  </li>
                </ul>
                <nav>
                  <div class="search-form">
                      <%= form_with url: search_path, method: :get, local: true do |f| %>
                        <%= f.text_field :keyword, value: @keyword %>
                        <%= f.submit "検索" %>
                      <% end %>
                  </div>
                </nav>
              </div>
        </nav>
<% elsif admin_signed_in? %>
  <nav class="navbar navbar-expand-lg navbar-dark bg-info">
    <%= link_to "管理者画面", admin_homes_top_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "Customers",admin_customers_path, class:"nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Comment List", admin_comments_path, class:"nav-link" %>
          </li>
          <li class="nav-item active">
             <%= link_to "Post List", admin_posts_path, class:"nav-link" %>
          </li>
           <li class="nav-item active">
              <%= link_to "Log Out", destroy_admin_session_path, method: :delete, class: "nav-link text-white" %>
          </li>
        </ul>
      </div>
  </nav>
  <% else %>
    <nav class="navbar navbar-expand-lg navbar-dark bg-info">
　　  <%= link_to "Face Pallet", root_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "Post List",  posts_path, class:"nav-link" %>
          </li>
          <li class="nav-item active">
             <%= link_to "Sign Up", new_customer_registration_path, class:"nav-link" %>
          </li>
           <li class="nav-item active">
              <%= link_to "Log In", customer_session_path, class: "nav-link text-white" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Guest Log In",  customers_guest_sign_in_path, method: :post, class: "nav-link text-white" %>
          </li>
        </ul>
      </div>
    </nav>
<% end %>
    <%= yield %>
  </body>
</html>